name: Build

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: ${{ matrix.board }}
    container: golioth/golioth-zephyr-base:0.16.3-SDK-v0
    env:
      ZEPHYR_SDK_INSTALL_DIR: /opt/toolchains/zephyr-sdk-0.16.3
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - manifest:    west.yml
            board:       esp32s3_devkitm
            binary_blob: hal_espressif
          - manifest:    west.yml
            board:       mimxrt1024_evk
          - manifest:    west-ncs.yml
            board:       nrf7002dk_nrf5340_cpuapp
          - manifest:    west-ncs.yml
            board:       nrf9160dk_nrf9160_ns
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v4
      with:
        path: app

    - name: Init and update west
      run: |
        mkdir -p .west
        cat <<EOF > .west/config
        [manifest]
        path = app
        file = ${{ matrix.manifest }}
        EOF

        west update -o=--depth=1 -n

        pip3 install -r deps/zephyr/scripts/requirements-base.txt
        pip3 install -r deps/zephyr/scripts/requirements-build-test.txt
        pip3 install -r deps/zephyr/scripts/requirements-run-test.txt
        # Needed for TF-M
        pip3 install cryptography==41.0.7 pyasn1 pyyaml cbor>=1.0.0 imgtool>=1.9.0 jinja2 click

    - name: Download binary blobs
      if: ${{ matrix.binary_blob }}
      run: |
        west blobs fetch ${{ matrix.binary_blob }}

    - name: Compile
      shell: bash
      run: west  build -p -b ${{ matrix.board }} app
